export const characterTypes = {
    GET_CHARACTERS: "GET_CHARACTERS",
    GET_CHARACTERS_SEARCHED: "GET_CHARACTERS_SEARCHED",
    GET_CHARACTER: "GET_CHARACTER",
    LOADING: "LOADING",
    ERROR: "ERROR",
    PAGECHANGE: "PAGECHANGE"
}