export const characterTypes = {
    GET_CHARACTERS: "GET_CHARACTERS",
    GET_CHARACTERS_SEARCHED: "GET_CHARACTERS_SEARCHED",
    GET_CHARACTER: "GET_CHARACTER",
    GET_CHARACTERS_BY_QUERY: "GET_CHARACTERS_BY_QUERY",
    ADD_CHARACTER_FAV: "ADD_CHARACTER_FAV",
    REMOVE_CHARACTER_DEV: "REMOVE_CHARACTER_DEV",
    LOADING: "LOADING",
    ERROR: "ERROR",
    PAGECHANGE: "PAGECHANGE"
}